version: "3.9"

services:
  api:
    build: .
    container_name: delivery_api
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGO_URI: mongodb://mongo:27017/delivery
      PARTNER_API_KEY: change-me-in-production
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run start:dev

  mongo:
    image: mongo:7
    container_name: delivery_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: